general {
    lock_cmd = pidof hyprlock || hyprlock 
}

listener { 
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # turn off keyboard backlight.
    # on-timeout = loginctl lock-session                   # locks screen on idle
    on-resume = brightnessctl -rd rgb:kbd_backlight        # turn on keyboard backlight.
}
